[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-hardware-inspector"
version = "0.1.0"
description = "Herramienta para inspeccionar hardware/sofware y sugerir configuración de LLM."
authors = [
  { name = "VladimirGonzalez", email = "tu-email@example.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
"Source Code" = "https://github.com/VladimirGonzalez/llm-hardware-inspector"
"Bug Tracker" = "https://github.com/VladimirGonzalez/llm-hardware-inspector/issues"

[project.dependencies]
psutil = "*"
GPUtil = "*"
py-cpuinfo = {optional = true}
pynvml = {optional = true}
torch = {optional = true}
tensorflow = {optional = true}
